version: "3.9"

services:
  fastapi:
    build: .
    container_name: api-crud-usuarios
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./app.db:/app/.db         
    env_file:
      - .env
    restart: always